version: "3.7"
services:
  deft-bridge-validator-server:
    # build: .
    image: deft-bridge-validator-server
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 1034:3001
  redis:
    image: redis:latest
    restart: always
    volumes:
      - deft-validator-redis:/data

volumes:
  deft-validator-redis:
