/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingInterface extends ethers.utils.Interface {
  functions: {
    "bulkEndStake(uint256[])": FunctionFragment;
    "bulkScrapeStake(uint256[])": FunctionFragment;
    "bulkStartStake(tuple[])": FunctionFragment;
    "bulkTransferOwnership(uint256[],address)": FunctionFragment;
    "bumpDays(uint256)": FunctionFragment;
    "endStake(uint256,uint256)": FunctionFragment;
    "scrapeStake(uint256,uint256)": FunctionFragment;
    "startStake(tuple)": FunctionFragment;
    "transferOwnership(uint256,address)": FunctionFragment;
    "updateAllSnapshots()": FunctionFragment;
    "updateSnapshots(uint256)": FunctionFragment;
    "cachedInterestPerShare(uint256)": FunctionFragment;
    "dailySnapshots(uint256)": FunctionFragment;
    "getCachedInterestPerShareLength()": FunctionFragment;
    "getCurrentCachedPerShareDay()": FunctionFragment;
    "getCurrentOneDay()": FunctionFragment;
    "getDailySnapshotsLength()": FunctionFragment;
    "getInterestById(uint256,uint256)": FunctionFragment;
    "getInterestByStake(tuple,uint256)": FunctionFragment;
    "getPenaltyById(uint256,uint256,uint256)": FunctionFragment;
    "getPenaltyByStake(tuple,uint256,uint256)": FunctionFragment;
    "getSharesCountById(uint256,uint256)": FunctionFragment;
    "getSharesCountByStake(tuple,uint256)": FunctionFragment;
    "stakes(uint256)": FunctionFragment;
    "totalStaked()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bulkEndStake",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bulkScrapeStake",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bulkStartStake",
    values: [{ stakedAmount: BigNumberish; lockedForXDays: BigNumberish }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bulkTransferOwnership",
    values: [BigNumberish[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "bumpDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endStake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scrapeStake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startStake",
    values: [{ stakedAmount: BigNumberish; lockedForXDays: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllSnapshots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSnapshots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cachedInterestPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailySnapshots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCachedInterestPerShareLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentCachedPerShareDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentOneDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDailySnapshotsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterestById",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInterestByStake",
    values: [
      {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenaltyById",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenaltyByStake",
    values: [
      {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharesCountById",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharesCountByStake",
    values: [
      {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bulkEndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bulkScrapeStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bulkStartStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bulkTransferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bumpDays", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scrapeStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllSnapshots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSnapshots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedInterestPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailySnapshots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCachedInterestPerShareLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentCachedPerShareDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentOneDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailySnapshotsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterestById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterestByStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenaltyById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenaltyByStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharesCountById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharesCountByStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;

  events: {
    "CachedInterestPerShareSealed(uint256,uint256,uint256)": EventFragment;
    "DailySnapshotSealed(uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "StakeEnded(uint256,uint256,uint256,uint256)": EventFragment;
    "StakeOwnerChanged(uint256,address)": EventFragment;
    "StakeStarted(uint256,address,uint256,uint256,uint256,uint256)": EventFragment;
    "StakeUpdated(uint256,uint256,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "CachedInterestPerShareSealed"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DailySnapshotSealed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeEnded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeOwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeUpdated"): EventFragment;
}

export type CachedInterestPerShareSealedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    sealedDay: BigNumber;
    sealedCachedDay: BigNumber;
    cachedInterestPerShare: BigNumber;
  }
>;

export type DailySnapshotSealedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    sealedDay: BigNumber;
    inflationAmount: BigNumber;
    totalShares: BigNumber;
    sharePrice: BigNumber;
    totalStaked: BigNumber;
    totalSupply: BigNumber;
  }
>;

export type StakeEndedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber] & {
    stakeId: BigNumber;
    endDay: BigNumber;
    interest: BigNumber;
    penalty: BigNumber;
  }
>;

export type StakeOwnerChangedEvent = TypedEvent<
  [BigNumber, string] & { stakeId: BigNumber; newOwner: string }
>;

export type StakeStartedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
    stakeId: BigNumber;
    owner: string;
    stakedAmount: BigNumber;
    startDay: BigNumber;
    lockedForXDays: BigNumber;
    sharesCount: BigNumber;
  }
>;

export type StakeUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    stakeId: BigNumber;
    lockedForXDays: BigNumber;
    sharesCount: BigNumber;
  }
>;

export class Staking extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingInterface;

  functions: {
    bulkEndStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bulkScrapeStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bulkStartStake(
      _startStakes: {
        stakedAmount: BigNumberish;
        lockedForXDays: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bulkTransferOwnership(
      stakeIds: BigNumberish[],
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bumpDays(
      numDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scrapeStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startStake(
      _startStake: { stakedAmount: BigNumberish; lockedForXDays: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      stakeId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAllSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSnapshots(
      givenDay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cachedInterestPerShare(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dailySnapshots(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        inflationAmount: BigNumber;
        totalShares: BigNumber;
        sharePrice: BigNumber;
      }
    >;

    getCachedInterestPerShareLength(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCurrentCachedPerShareDay(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCurrentOneDay(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDailySnapshotsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getInterestById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getInterestByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPenaltyById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPenaltyByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSharesCountById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSharesCountByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    stakes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        owner: string;
        stakedAmount: BigNumber;
        startDay: BigNumber;
        lockedForXDays: BigNumber;
        endDay: BigNumber;
      }
    >;

    totalStaked(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  bulkEndStake(
    stakeIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bulkScrapeStake(
    stakeIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bulkStartStake(
    _startStakes: {
      stakedAmount: BigNumberish;
      lockedForXDays: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bulkTransferOwnership(
    stakeIds: BigNumberish[],
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bumpDays(
    numDays: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endStake(
    stakeId: BigNumberish,
    _bumpDays: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scrapeStake(
    stakeId: BigNumberish,
    _bumpDays: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startStake(
    _startStake: { stakedAmount: BigNumberish; lockedForXDays: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    stakeId: BigNumberish,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAllSnapshots(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSnapshots(
    givenDay: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cachedInterestPerShare(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  dailySnapshots(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      inflationAmount: BigNumber;
      totalShares: BigNumber;
      sharePrice: BigNumber;
    }
  >;

  getCachedInterestPerShareLength(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCurrentCachedPerShareDay(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentOneDay(overrides?: CallOverrides): Promise<BigNumber>;

  getDailySnapshotsLength(overrides?: CallOverrides): Promise<BigNumber>;

  getInterestById(
    stakeId: BigNumberish,
    givenDay: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getInterestByStake(
    stake: {
      owner: string;
      stakedAmount: BigNumberish;
      startDay: BigNumberish;
      lockedForXDays: BigNumberish;
      endDay: BigNumberish;
    },
    givenDay: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPenaltyById(
    stakeId: BigNumberish,
    givenDay: BigNumberish,
    interest: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPenaltyByStake(
    stake: {
      owner: string;
      stakedAmount: BigNumberish;
      startDay: BigNumberish;
      lockedForXDays: BigNumberish;
      endDay: BigNumberish;
    },
    givenDay: BigNumberish,
    interest: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSharesCountById(
    stakeId: BigNumberish,
    givenDay: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSharesCountByStake(
    stake: {
      owner: string;
      stakedAmount: BigNumberish;
      startDay: BigNumberish;
      lockedForXDays: BigNumberish;
      endDay: BigNumberish;
    },
    givenDay: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  stakes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      owner: string;
      stakedAmount: BigNumber;
      startDay: BigNumber;
      lockedForXDays: BigNumber;
      endDay: BigNumber;
    }
  >;

  totalStaked(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    bulkEndStake(
      stakeIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    bulkScrapeStake(
      stakeIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    bulkStartStake(
      _startStakes: {
        stakedAmount: BigNumberish;
        lockedForXDays: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    bulkTransferOwnership(
      stakeIds: BigNumberish[],
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    bumpDays(numDays: BigNumberish, overrides?: CallOverrides): Promise<void>;

    endStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    scrapeStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    startStake(
      _startStake: { stakedAmount: BigNumberish; lockedForXDays: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      stakeId: BigNumberish,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAllSnapshots(overrides?: CallOverrides): Promise<void>;

    updateSnapshots(
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cachedInterestPerShare(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dailySnapshots(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        inflationAmount: BigNumber;
        totalShares: BigNumber;
        sharePrice: BigNumber;
      }
    >;

    getCachedInterestPerShareLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentCachedPerShareDay(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentOneDay(overrides?: CallOverrides): Promise<BigNumber>;

    getDailySnapshotsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getInterestById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInterestByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenaltyById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenaltyByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSharesCountById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSharesCountByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stakes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        owner: string;
        stakedAmount: BigNumber;
        startDay: BigNumber;
        lockedForXDays: BigNumber;
        endDay: BigNumber;
      }
    >;

    totalStaked(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CachedInterestPerShareSealed(uint256,uint256,uint256)"(
      sealedDay?: null,
      sealedCachedDay?: null,
      cachedInterestPerShare?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      {
        sealedDay: BigNumber;
        sealedCachedDay: BigNumber;
        cachedInterestPerShare: BigNumber;
      }
    >;

    CachedInterestPerShareSealed(
      sealedDay?: null,
      sealedCachedDay?: null,
      cachedInterestPerShare?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      {
        sealedDay: BigNumber;
        sealedCachedDay: BigNumber;
        cachedInterestPerShare: BigNumber;
      }
    >;

    "DailySnapshotSealed(uint256,uint256,uint256,uint256,uint256,uint256)"(
      sealedDay?: null,
      inflationAmount?: null,
      totalShares?: null,
      sharePrice?: null,
      totalStaked?: null,
      totalSupply?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        sealedDay: BigNumber;
        inflationAmount: BigNumber;
        totalShares: BigNumber;
        sharePrice: BigNumber;
        totalStaked: BigNumber;
        totalSupply: BigNumber;
      }
    >;

    DailySnapshotSealed(
      sealedDay?: null,
      inflationAmount?: null,
      totalShares?: null,
      sharePrice?: null,
      totalStaked?: null,
      totalSupply?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        sealedDay: BigNumber;
        inflationAmount: BigNumber;
        totalShares: BigNumber;
        sharePrice: BigNumber;
        totalStaked: BigNumber;
        totalSupply: BigNumber;
      }
    >;

    "StakeEnded(uint256,uint256,uint256,uint256)"(
      stakeId?: null,
      endDay?: null,
      interest?: null,
      penalty?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber],
      {
        stakeId: BigNumber;
        endDay: BigNumber;
        interest: BigNumber;
        penalty: BigNumber;
      }
    >;

    StakeEnded(
      stakeId?: null,
      endDay?: null,
      interest?: null,
      penalty?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber],
      {
        stakeId: BigNumber;
        endDay: BigNumber;
        interest: BigNumber;
        penalty: BigNumber;
      }
    >;

    "StakeOwnerChanged(uint256,address)"(
      stakeId?: null,
      newOwner?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { stakeId: BigNumber; newOwner: string }
    >;

    StakeOwnerChanged(
      stakeId?: null,
      newOwner?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { stakeId: BigNumber; newOwner: string }
    >;

    "StakeStarted(uint256,address,uint256,uint256,uint256,uint256)"(
      stakeId?: null,
      owner?: null,
      stakedAmount?: null,
      startDay?: null,
      lockedForXDays?: null,
      sharesCount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        stakeId: BigNumber;
        owner: string;
        stakedAmount: BigNumber;
        startDay: BigNumber;
        lockedForXDays: BigNumber;
        sharesCount: BigNumber;
      }
    >;

    StakeStarted(
      stakeId?: null,
      owner?: null,
      stakedAmount?: null,
      startDay?: null,
      lockedForXDays?: null,
      sharesCount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        stakeId: BigNumber;
        owner: string;
        stakedAmount: BigNumber;
        startDay: BigNumber;
        lockedForXDays: BigNumber;
        sharesCount: BigNumber;
      }
    >;

    "StakeUpdated(uint256,uint256,uint256)"(
      stakeId?: null,
      lockedForXDays?: null,
      sharesCount?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { stakeId: BigNumber; lockedForXDays: BigNumber; sharesCount: BigNumber }
    >;

    StakeUpdated(
      stakeId?: null,
      lockedForXDays?: null,
      sharesCount?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { stakeId: BigNumber; lockedForXDays: BigNumber; sharesCount: BigNumber }
    >;
  };

  estimateGas: {
    bulkEndStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bulkScrapeStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bulkStartStake(
      _startStakes: {
        stakedAmount: BigNumberish;
        lockedForXDays: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bulkTransferOwnership(
      stakeIds: BigNumberish[],
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bumpDays(
      numDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scrapeStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startStake(
      _startStake: { stakedAmount: BigNumberish; lockedForXDays: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      stakeId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAllSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSnapshots(
      givenDay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cachedInterestPerShare(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dailySnapshots(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCachedInterestPerShareLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentCachedPerShareDay(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentOneDay(overrides?: CallOverrides): Promise<BigNumber>;

    getDailySnapshotsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getInterestById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInterestByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenaltyById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenaltyByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSharesCountById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSharesCountByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stakes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    totalStaked(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bulkEndStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bulkScrapeStake(
      stakeIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bulkStartStake(
      _startStakes: {
        stakedAmount: BigNumberish;
        lockedForXDays: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bulkTransferOwnership(
      stakeIds: BigNumberish[],
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bumpDays(
      numDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scrapeStake(
      stakeId: BigNumberish,
      _bumpDays: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startStake(
      _startStake: { stakedAmount: BigNumberish; lockedForXDays: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      stakeId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAllSnapshots(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSnapshots(
      givenDay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cachedInterestPerShare(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dailySnapshots(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCachedInterestPerShareLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentCachedPerShareDay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentOneDay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDailySnapshotsLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInterestById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInterestByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPenaltyById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPenaltyByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSharesCountById(
      stakeId: BigNumberish,
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSharesCountByStake(
      stake: {
        owner: string;
        stakedAmount: BigNumberish;
        startDay: BigNumberish;
        lockedForXDays: BigNumberish;
        endDay: BigNumberish;
      },
      givenDay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stakes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalStaked(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
