version: "3.7"
services:
  deft-detector:
    image: bot-detector-server
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 1105:3001
    env_file:
      - ./.env-secret
    environment:
      - FETCH_AT_ONCE=3500
      - COMMON_PROVIDER_DEV=https://secret:X4gDeGtfQy2M@eth-node.valar-solutions.com
      - DEFT_TOKEN_START_BLOCK_DEV=12497900
      - DEFT_TOKEN_DEV=0xdef1fac7bf08f173d286bbbdcbeeade695129840
      - DEFT_UNISWAP_PAIR_DEV=0xfa6687922bf40ff51bcd45f9fd339215a4869d82
      - IS_CONTRACT_BULK_DEV=0x13882970C480EaFe5493Ef3DE2c6EF3DFA68E1F7
      - WETH_TOKEN_DEV=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
      - DEFT_STORAGE_DEV=0x2b6a3d2068773B53fC1aC0373Ef581b31d65B4Da

  lambo-detector:
    image: bot-detector-server
    environment:
      NODE_ENV: production
    restart: always
    env_file:
      - ./.env-secret
    environment:
      - FETCH_AT_ONCE=3500
      - COMMON_PROVIDER_DEV=https://secret:X4gDeGtfQy2M@eth-node.valar-solutions.com
      - DEFT_TOKEN_START_BLOCK_DEV=12756491
      - DEFT_TOKEN_DEV=0x44EB8f6C496eAA8e0321006d3c61d851f87685BD
      - DEFT_UNISWAP_PAIR_DEV=0x5eeA2C5f1139f0f94b1F4064D383157037385b92
      - IS_CONTRACT_BULK_DEV=0x13882970C480EaFe5493Ef3DE2c6EF3DFA68E1F7
      - WETH_TOKEN_DEV=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
      - DEFT_STORAGE_DEV=0x2b6a3d2068773B53fC1aC0373Ef581b31d65B4Da

  redis:
    image: redis:latest
    restart: always
    volumes:
      - shared-redis:/data

volumes:
  shared-redis:
