version: "3.7"
services:
  lambo-detector:
    image: bot-detector-server
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 1107:3001
    env_file:
      - ./.env-lambo
  redis:
    image: redis:latest
    restart: always
    volumes:
      - shared-redis:/data

volumes:
  shared-redis:
