version: "3.7"
services:
  deft-supply-marketcap-server:
    # build: .
    image: deft-supply-marketcap-server
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 1030:3001
  redis:
    image: redis:latest
    restart: always
    volumes:
      - deft-supply-redis:/data

volumes:
  deft-supply-redis:
