version: "3.7"
services:
  deft-detector:
    image: presale-factory-server
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 1150:3001
  redis:
    image: redis:latest
    restart: always
