/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NoBotsTechV2Contract } from "./NoBotsTechV2Contract";

export { NoBotsTechV2Contract__factory } from "./factories/NoBotsTechV2Contract__factory";
