/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DefiFactoryTokenContract } from "./DefiFactoryTokenContract";

export { DefiFactoryTokenContract__factory } from "./factories/DefiFactoryTokenContract__factory";
